package ru.m210projects.Wang;

import static ru.m210projects.Wang.Type.MyTypes.*;

public class Stag {

	public static final int STAGF_MATCH_TAG2 = (BIT(31));

	public static final int SECT_SINK = 0;  
	public static final int SECT_OPERATIONAL = 1;  
	public static final int SECT_CURRENT = 3;  
	public static final int SECT_NO_RIDE = 5; 
	public static final int SECT_DIVE_AREA = 7; // STAGF_MATCH_TAG2); // 
	public static final int SECT_UNDERWATER = 8; // STAGF_MATCH_TAG2); //
	public static final int SECT_UNDERWATER2 = 9; // STAGF_MATCH_TAG2); //
	public static final int SO_ANGLE = 16;  
	public static final int SECT_FLOOR_PAN = 19; 
	public static final int SECT_CEILING_PAN = 21; 
	public static final int SECT_WALL_PAN_SPEED = 23;  
	public static final int SECT_WALL_PAN_ANG = 24; 
	public static final int SECT_DEBRIS_SEWER = 25; 
	public static final int SECT_SO_CENTER = 27; 
	public static final int SECT_MATCH = 28; // STAGF_MATCH_TAG2); // 
	public static final int SECT_LOCK_DOOR = 29;  
	public static final int SPRI_CLIMB_MARKER = 30;  
	public static final int SECT_SO_SPRITE_OBJ = 31; 
	public static final int SECT_SO_DONT_BOB = 32; 
	public static final int SECT_SO_SINK_DEST = 33;  
	public static final int SECT_SO_DONT_SINK = 34; 
	public static final int SECT_SO_FORM_WHIRLPOOL = 37;  
	public static final int SECT_ACTOR_BLOCK = 38;  
	public static final int SECT_SO_CLIP_DIST = 39; 
	public static final int MULTI_PLAYER_START = 42; 
	public static final int FIREBALL_TRAP = 43; // STAGF_MATCH_TAG2); // 
	public static final int BOLT_TRAP = 44; // STAGF_MATCH_TAG2); // 
	public static final int SECT_SO_DONT_ROTATE = 45; 
	public static final int PARALLAX_LEVEL = 46;  
	public static final int SECT_DONT_COPY_PALETTE = 47; 
	public static final int MULTI_COOPERATIVE_START = 48; 
	public static final int SO_SET_SPEED = 49;  
	public static final int SO_SPIN = 50;  
	public static final int SO_SPIN_REVERSE = 51;  
	public static final int SO_BOB_START = 52;  
	public static final int SO_BOB_SPEED = 53; 
	public static final int SO_TURN_SPEED = 55; 
	public static final int LAVA_ERUPT = 56; 
	public static final int SECT_EXPLODING_CEIL_FLOOR = 57; // STAGF_MATCH_TAG2); // 
	public static final int SECT_COPY_DEST = 58; // STAGF_MATCH_TAG2); //
	public static final int SECT_COPY_SOURCE = 59; // STAGF_MATCH_TAG2); //
	public static final int SO_SHOOT_POINT = 62;  
	public static final int SPEAR_TRAP = 63; // STAGF_MATCH_TAG2); //
	public static final int SO_SYNC1 = 64;  
	public static final int SO_SYNC2 = 65; 
	public static final int DEMO_CAMERA = 66;  
	public static final int SO_LIMIT_TURN = 68; 
	public static final int SPAWN_SPOT = 69; // STAGF_MATCH_TAG2); //
	public static final int SO_MATCH_EVENT = 70; // STAGF_MATCH_TAG2); //
	public static final int SO_SLOPE_FLOOR_TO_POINT = 71;  
	public static final int SO_SLOPE_CEILING_TO_POINT = 72; 
	public static final int SO_TORNADO = 73;  
	public static final int SO_FLOOR_MORPH = 74;  
	public static final int SO_AMOEBA = 75; 
	public static final int SO_MAX_DAMAGE = 76;  
	public static final int SO_RAM_DAMAGE = 77;  
	public static final int SO_CLIP_BOX = 78; 
	public static final int SO_SLIDE = 79; 
	public static final int SO_KILLABLE = 80;  
	public static final int SO_AUTO_TURRET = 81; 
	public static final int SECT_DAMAGE = 82; 
	public static final int WARP_TELEPORTER = 84; // STAGF_MATCH_TAG2); // 
	public static final int WARP_CEILING_PLANE = 85; // STAGF_MATCH_TAG2); //
	public static final int WARP_FLOOR_PLANE = 86; // STAGF_MATCH_TAG2); // 
	public static final int WARP_COPY_SPRITE1 = 87; // STAGF_MATCH_TAG2); //
	public static final int WARP_COPY_SPRITE2 = 88; // STAGF_MATCH_TAG2); //
	public static final int PLAX_GLOB_Z_ADJUST = 90;  
	public static final int PLAX_Z_ADJUST = 91; 
	public static final int SECT_VATOR = 92; // STAGF_MATCH_TAG2); // 
	public static final int SECT_VATOR_DEST = 94; 
	public static final int CEILING_Z_ADJUST = 97;  
	public static final int FLOOR_Z_ADJUST = 98;  
	public static final int FLOOR_SLOPE_DONT_DRAW = 99; 
	public static final int SO_SCALE_INFO = 100;  
	public static final int SO_SCALE_POINT_INFO = 101;  
	public static final int SO_SCALE_XY_MULT = 102; 
	public static final int SECT_WALL_MOVE = 103; // STAGF_MATCH_TAG2); //
	public static final int SECT_WALL_MOVE_CANSEE = 104; // STAGF_MATCH_TAG2); //
	public static final int SECT_SPIKE = 106; // STAGF_MATCH_TAG2); // 
	public static final int LIGHTING = 108; // STAGF_MATCH_TAG2); // 
	public static final int LIGHTING_DIFFUSE = 109; // STAGF_MATCH_TAG2); //
	public static final short VIEW_THRU_CEILING = 120;  
	public static final short VIEW_THRU_FLOOR = 121; 
	public static final short VIEW_LEVEL1 = 110;  
	public static final short VIEW_LEVEL2 = 111;  
	public static final short VIEW_LEVEL3 = 112;  
	public static final short VIEW_LEVEL4 = 113;  
	public static final short VIEW_LEVEL5 = 114; 
	public static final short VIEW_LEVEL6 = 115; 
	public static final int SO_WALL_DONT_MOVE_UPPER = 130; // STAGF_MATCH_TAG2); // 
	public static final int SO_WALL_DONT_MOVE_LOWER = 131; // STAGF_MATCH_TAG2); //
	public static final int BREAKABLE = 132; // STAGF_MATCH_TAG2); // 
	public static final int QUAKE_SPOT = 133; // STAGF_MATCH_TAG2); // 
	public static final int SOUND_SPOT = 134; // STAGF_MATCH_TAG2); //
	public static final int SLIDE_SECTOR = 135;  
	public static final int CEILING_FLOOR_PIC_OVERRIDE = 136;  
	public static final int TRIGGER_SECTOR = 140; // STAGF_MATCH_TAG2); //
	public static final int DELETE_SPRITE = 141; // STAGF_MATCH_TAG2); // 
	public static final int SECT_ROTATOR = 143; // STAGF_MATCH_TAG2); //
	public static final int SECT_ROTATOR_PIVOT = 144; // STAGF_MATCH_TAG2); // 
	public static final int SECT_SLIDOR = 145; // STAGF_MATCH_TAG2); //
	public static final int SECT_CHANGOR = 146; // STAGF_MATCH_TAG2); // 
	public static final int SO_DRIVABLE_ATTRIB = 147;  
	public static final int WALL_DONT_STICK = 148;  
	public static final int SPAWN_ITEMS = 149; 
	public static final int STOP_SOUND_SPOT = 150; 
	public static final int BOUND_FLOOR_UPPER = 200;  
	public static final int BOUND_FLOOR_LOWER = 201;  
	public static final int BOUND_FLOOR_BASE_OFFSET = 202; 
	public static final int BOUND_FLOOR_OFFSET = 203; 
	public static final int BOUND_SO_UPPER0 = 500;  
	public static final int BOUND_SO_LOWER0 = 501;  
	public static final int BOUND_SO_UPPER1 = 505;  
	public static final int BOUND_SO_LOWER1 = 506; 
	public static final int BOUND_SO_UPPER2 = 510;  
	public static final int BOUND_SO_LOWER2 = 511;  
	public static final int BOUND_SO_UPPER3 = 515;  
	public static final int BOUND_SO_LOWER3 = 516; 
	public static final int BOUND_SO_UPPER4 = 520;  
	public static final int BOUND_SO_LOWER4 = 521;  
	public static final int BOUND_SO_UPPER5 = 525;  
	public static final int BOUND_SO_LOWER5 = 526; 
	public static final int BOUND_SO_UPPER6 = 530;  
	public static final int BOUND_SO_LOWER6 = 531;  
	public static final int BOUND_SO_UPPER7 = 535;  
	public static final int BOUND_SO_LOWER7 = 536; 
	public static final int BOUND_SO_UPPER8 = 540;  
	public static final int BOUND_SO_LOWER8 = 541;  
	public static final int BOUND_SO_UPPER9 = 545;  
	public static final int BOUND_SO_LOWER9 = 546; 
	public static final int BOUND_SO_UPPER10 = 550;  
	public static final int BOUND_SO_LOWER10 = 551;  
	public static final int BOUND_SO_UPPER11 = 555;  
	public static final int BOUND_SO_LOWER11 = 556; 
	public static final int BOUND_SO_UPPER12 = 560;  
	public static final int BOUND_SO_LOWER12 = 561; 
	public static final int BOUND_SO_UPPER13 = 565;  
	public static final int BOUND_SO_LOWER13 = 566; 
	public static final int BOUND_SO_UPPER14 = 570;  
	public static final int BOUND_SO_LOWER14 = 571;  
	public static final int BOUND_SO_UPPER15 = 575;  
	public static final int BOUND_SO_LOWER15 = 576; 
	public static final int BOUND_SO_UPPER16 = 580;  
	public static final int BOUND_SO_LOWER16 = 581;  
	public static final int BOUND_SO_UPPER17 = 585;  
	public static final int BOUND_SO_LOWER17 = 586; 
	public static final int BOUND_SO_UPPER18 = 590;  
	public static final int BOUND_SO_LOWER18 = 591;  
	public static final int BOUND_SO_UPPER19 = 595;  
	public static final int BOUND_SO_LOWER19 = 596; 
	public static final int TV_CAMERA = 1000;  
	public static final int AMBIENT = 1002;  
	public static final int ECHOSPOT = 1005;  
	public static final int DRIP_GENERATOR = 1006;

}
