package ru.m210projects.Witchaven;

import static ru.m210projects.Witchaven.Main.*;

public class Names {
	
	public static final int TILES000_START = 0;
	public static final int SLIME = 5;
	public static final int DRYWATER = 22;
	public static final int DRYSLIME = 33;
	public static final int COOLLAVA = 58;
	public static final int ANILAVA = 61;
	public static final int LAVA1 = 62;
	public static final int WOODPLANK = 68;
	public static final int SKY = 75;
	public static final int LAVA = 79;
	public static final int LAVA2 = 80;
	public static final int HEALTHWATER = 86;
	public static final int WATER = 90;
	public static final int COOLLAVA2 = 103;
	public static final int SPLASHAROO = 160;
	public static final int LASTSPLASHAROO = 166;
	public static final int SKY2 = 167;
	public static final int SKY3 = 168;
	public static final int SKY4 = 169;
	public static final int SKY5 = 170;
	public static final int SKY6 = 171;
	public static final int SKY7 = 172;
	public static final int TILES001_START = 247;
	public static final int GIFTBOX = 260;
	public static final int OPENCHEST = 263;
	public static final int BARREL = 269;
	public static final int SPACEPLANK = 271;
	public static final int PENTADOOR1 = 280;
	public static final int PENTADOOR2 = 281;
	public static final int ROPEDOOR = 282;
	public static final int TELEPAD = 291;
	public static final int BULLET = 294;
	public static final int PINE = 308;
	public static final int SWINGDOOR = 324;
	public static final int SWINGDOOR2 = 325;
	public static final int SWINGDOOR3 = 326;
	public static final int BAT = 330;
	public static final int FBARREL = 340;
	public static final int FBARRELFALL = 341;
	public static final int FSHATTERBARREL = 342;
	public static final int BOULDER = 361;
	public static final int PULLCHAIN1 = 370;
	public static final int PULLCHAIN2 = 371;
	public static final int PULLCHAIN3 = 372;
	public static final int SAPHIRERING = 373;
	public static final int TALLSWING = 385;
	public static final int TALLSWING2 = 386;
	public static final int SPARKFX = 390;
	public static final int VASEA = 392;
	public static final int VASEB = 393;
	public static final int VASEC = 394;
	public static final int HEALTHPOTION = 401;
	public static final int FIREWALKPOTION = 402;
	public static final int STRENGTHPOTION = 403;
	public static final int INVISIBLEPOTION = 404;
	public static final int ARMORPOTION = 406;
	public static final int LAVASPLASH = 423;
	public static final int LASTLAVASPLASH = 437;
	public static final int SPIKEBLADE = 461;
	public static final int SPIKE = 462;
	public static final int SPIKEPOLE = 463;
	public static final int HORIZSPIKEPOLE = 464;
	public static final int HORIZSPIKE = 465;
	public static final int HORIZSPIKEBLADE = 466;
	public static final int GEARSSTART = 467;
	public static final int GEARSEND = 474;
	public static final int SWINGHOLE = 476;
	public static final int SWINGGATE = 477;
	public static final int SWINGGATE2 = 478;
	public static final int WOODGEARSSTART = 483;
	public static final int WOODGEARSEND = 486;
	public static final int SQUAREGRATE = 490;
	public static final int MAINMENU = 500;
	public static final int TITLEPIC = 501;
	public static final int SAVEPIC = 502;
	public static final int SAVENUMBERS = 503;
	public static final int LOADPIC = 504;
	public static final int AREYOUSURE = 505;
	public static final int BLOODGORERED = 506;
	public static final int DIFFICULTRED = 507;
	public static final int BLOODGOREGREEN = 508;
	public static final int DIFFICULTGREEN = 509;
	public static final int HORNYSKULL1 = 510;
	public static final int HORNYSKULL2 = 511;
	public static final int HORNYSKULL3 = 512;
	public static final int HORNYSKULL4 = 513;
	public static final int HORNYBACK = 514;
	public static final int LOADRED = 515;
	public static final int SAVERED = 516;
	public static final int LOADGREEN = 517;
	public static final int SAVEGREEN = 518;
	public static final int MENUSELECTIONS = 519;
	public static final int NEWGAMEGREEN = 520;
	public static final int LOADSAVEGREEN = 521;
	public static final int BLOODGOREGREEN2 = 522;
	public static final int HELPGREEN = 523;
	public static final int QUITGREEN = 524;
	public static final int NOGORESHADOW = 525;
	public static final int NOGORESOLID = 526;
	public static final int GORESHADOW = 527;
	public static final int GORESOLID = 528;
	public static final int VDARK = 529;
	public static final int MDARK = 530;
	public static final int FLICKER = 531;
	public static final int XDARK = 532;
	public static final int BACKGROUND = 536;
	public static final int WALLARROW = 537;
	public static final int MUHANDS = 538;
	public static final int STATUSBAR = 545;
	public static final int ORB1 = 546;
	public static final int ORB2 = 547;
	public static final int FLASKBLUE = 548;
	public static final int FLASKGREEN = 549;
	public static final int FLASKOCHRE = 550;
	public static final int FLASKRED = 551;
	public static final int FLASKTAN = 552;
	public static final int FLASKBLACK = 553;
	public static final int BGZERO = 554;
	public static final int BGONE = 555;
	public static final int BGTWO = 556;
	public static final int BGTHREE = 557;
	public static final int BGFOUR = 558;
	public static final int BGFIVE = 559;
	public static final int BGSIX = 560;
	public static final int BGSEVEN = 561;
	public static final int BGEIGHT = 562;
	public static final int BGNINE = 563;
	public static final int SCOREFONT = 564;
	public static final int MDONE = 565;
	public static final int MDTWO = 566;
	public static final int MDTHREE = 567;
	public static final int MDFOUR = 568;
	public static final int MDFIVE = 569;
	public static final int MDSIX = 570;
	public static final int MDSEVEN = 571;
	public static final int MDEIGHT = 572;
	public static final int MDNINE = 573;
	public static final int SMFONT = 574;
	public static final int SMONE = 575;
	public static final int SMTWO = 576;
	public static final int SMTHREE = 577;
	public static final int SMFOUR = 578;
	public static final int SMFIVE = 579;
	public static final int SMSIX = 580;
	public static final int SMSEVEN = 581;
	public static final int SMEIGHT = 582;
	public static final int SMNINE = 583;
	public static final int SCOREBACKPIC = 584;
	public static final int WEAPONBACKPIC = 585;
	public static final int HEALTHBACKPIC = 586;
	public static final int BOOKBACKPIC = 587;
	public static final int ORBBACKPIC = 588;
	public static final int POTIONBACKPIC = 589;
	public static final int POTIONARROW = 590;
	public static final int ORB3 = 595;
	public static final int ORB4 = 596;
	public static final int ORB5 = 597;
	public static final int ORB6 = 598;
	public static final int ORB7 = 599;
	public static final int ORB8 = 600;
	public static final int WAVES1_SND = 607;
	public static final int WAVES2_SND = 608;
	public static final int WIND1_SND = 609;
	public static final int WIND2_SND = 610;
	public static final int LAVA1_SND = 611;
	public static final int LAVA2_SND = 612;
	public static final int DIESPIKE = 613;
	public static final int SPELLBOOKBLANK = 618;
	public static final int SPELLBOOK2 = 627;
	public static final int SPELLBOOK3 = 636;
	public static final int CHUNK1 = 645;
	public static final int CHUNK2 = 646;
	public static final int CHUNK3 = 647;
	public static final int CHUNK4 = 648;
	public static final int PLASMA = 649;
	public static final int ANNIHILATE = 650;
	public static final int WILLOWEXPLO = 653;
	public static final int EXPLOSION = 656;
	public static final int FATSPANK = 658;
	public static final int MONSTERBALL = 660;
	public static final int ICECUBE = 663;
	public static final int DISTORTIONBLAST = 664;
	public static final int SPELLBOOKBACK = 665;
	public static final int WEAPON3 = 666;
	public static final int ORB = 674;
	public static final int SPAWN = 675;
	public static final int ARMOR = 676;
	public static final int POTION = 677;
	public static final int WEAPON = 678;
	public static final int COPYRIGHT = 679;
	public static final int DIAMONDRING = 694;
	public static final int SHADOWAMULET = 698;
	public static final int GLASSSKULL = 706;
	public static final int AHNK = 714;
	public static final int BLUESCEPTER = 718;
	public static final int YELLOWSCEPTER = 722;
	public static final int ADAMANTINERING = 726;
	public static final int ONYXRING = 730;
	public static final int TILES003_START = 736;
	public static final int KOBOLD = 737;
	public static final int KOBOLDATTACK = 762;
	public static final int KOBOLDDIE = 765;
	public static final int KOBOLDDEAD = 770;
	public static final int KOBOLDTORCH = 771;
	public static final int DEVILSTAND = 772;
	public static final int DEVIL = 777;
	public static final int DEVILATTACK = 797;
	public static final int DEVILPAIN = 809;
	public static final int DEVILDIE = 814;
	public static final int DEVILDEAD = 820;
	public static final int TILES004_START = 980;
	public static final int MINOTAUR = 981;
	public static final int MINOTAURATTACK = 1001;
	public static final int MINOTAURPAIN = 1012;
	public static final int MINOTAURDIE = 1017;
	public static final int MINOTAURDEAD = 1027;
	
	public static short KNIFEREADY;
	public static short KNIFEATTACK;
	public static short RFIST;
	public static short SWORDATTACK;
	public static short MORNINGSTAR;
	public static short BOWREADY;
	public static short BOWREADYEND;
	public static short BOWWALK;
	public static short KNIFEATTACK2;
	public static short SWORDPULL;
	public static short SWORDATTACK2;
	public static short MORNINGATTACK2;
	public static short MUMEDUSA;
	public static short MUTWOHANDS;
	public static short BMUTWOHANDS;
	public static short GOBSWORDPULL;
	public static short GOBSWORDATTACK;
	public static short GOBSWORDATTACK2;
	public static short BIGAXEATTACK;
	public static short BIGAXEATTACK2;
	public static short BIGAXEDRAW;
	public static short HALBERDATTACK1;
	public static short HALBERDATTACK2;
	public static short HALBERDDRAW;
	public static short PIKEDRAW;
	public static short PIKEATTACK1;
	public static short EXCALATTACK1;
	public static short EXCALATTACK2;
	public static short EXCALDRAW;
	public static short BIGAXEDRAW9;
	public static short BIGAXEDRAW10;
	public static short GEARS2START;
	public static short HORNEDSKULL;
	public static short THEFONT;
	public static short CRYSTALSTAFF;
	public static short TORCH;
	public static short WEAPON1;
	public static short WEAPON1A;
	public static short AMULETOFTHEMIST;
	public static short WEAPON2;
	public static short BRASSKEY;
	public static short BLACKKEY;
	public static short GLASSKEY;
	public static short IVORYKEY;
	public static short NEWCHUNK;
	public static short BOWLOFFIRE;
	public static short SPAWNFIREBALL;
	public static short PENTAGRAM;
	public static short THEHORN;
	public static short BOW;
	public static short SWINGGATE3;
	public static short PLATEARMOR;
	public static short HELMET;
	public static short CHAINMAIL;
	public static short SCROLLSCARE;
	public static short SCROLLNUKE;
	public static short SCROLLFLY;
	public static short SCROLLFIREBALL;
	public static short SCROLLFREEZE;
	public static short SCROLLNIGHT;
	public static short SCROLLMAGIC;
	public static short SCROLLOPEN;
	public static short LEATHERARMOR;
	public static short QUIVER;
	public static short SWINGGATE4;
	public static short SWINGGATE5;
	public static short SMOKEFX;
	public static short STANDINTORCH;
	public static short PENTADOOR3;
	public static short PENTADOOR4;
	public static short PENTADOOR5;
	public static short PENTADOOR6;
	public static short PENTADOOR7;
	public static short SCARY;
	public static short FISH;
	public static short LEVERUP;
	public static short LEVERDOWN;
	public static short SPAWNJAVLIN;
	public static short RAT;
	public static short GUARDIAN;
	public static short GUARDIANATTACK;
	public static short DART;
	public static short WEAPON4;
	public static short WEAPON6;
	public static short WEAPON5;
	public static short WEAPON5B;
	public static short THROWHALBERD;
	public static short WEAPON7;
	public static short THROWPIKE;
	public static short EXPLO2;
	public static short SHATTERVASE;
	public static short SHATTERVASE2;
	public static short SHATTERVASE3;
	public static short HANGMAN;
	public static short SKELETON;
	public static short SKELETONATTACK;
	public static short SKELETONSKULL;
	public static short SKELETONUP;
	public static short SKELETONDIE;
	public static short SKELETONDEAD;
	public static short BONECHUNK1;
	public static short BONECHUNKEND;
	public static short PIKEATTACK2;
	public static short GOBWEAPON;
	public static short SFLASKBLUE;
	public static short SFLASKGREEN;
	public static short SFLASKOCHRE;
	public static short SFLASKRED;
	public static short SFLASKTAN;
	public static short SFLASKBLACK;
	public static short SHEALTHFONT;
	public static short SSCOREFONT;
	public static short SPOTIONFONT;
	public static short SPOTIONBACKPIC;
	public static short SPOTIONARROW;
	public static short SSPELLBOOKBLANK;
	public static short SSPELLBOOK2;
	public static short SSPELLBOOK3;
	public static short SSPELLBOOK4;
	public static short SSPELLBOOK5;
	public static short SSPELLBOOK6;
	public static short SSPELLBOOK7;
	public static short SSPELLBOOK8;
	public static short SARROWS;
	public static short SPLAYERLVL;
	public static short SSTATUSBAR;
	public static short SKEYBLANK;
	public static short SKEYBRASS;
	public static short SKEYBLACK;
	public static short SKEYGLASS;
	public static short SKEYIVORY;
	public static short SHEALTHBACK;
	public static short SSCOREBACKPIC;
	public static short SNDEFFECT;
	public static short SNDLOOP;
	public static short SNDLOOPOFF;
	public static short BROWNCHUNKSTART;
	public static short GREYCHUNKSTART;
	public static short REDCHUNKSTART;
	public static short GREENCHUNKSTART;
	public static short TANCHUNKSTART;
	public static short WILLOW;
	public static short SPIKES;
	public static short STHEFLAG;
	public static short GRONHALATTACK;
	public static short GRONHALATTACKEND;
	public static short GROLHALREADY;
	public static short GRONHALREADYEND;
	public static short GRONHAL;
	public static short GRONHALPAIN;
	public static short GRONHALDIE;
	public static short GRONSWATTACK;
	public static short GRONSW;
	public static short GRONSWPAIN;
	public static short GRONSWDIE;
	public static short GRONMUATTACK;
	public static short GRONDIE;
	public static short GRONDEAD;
	public static short GRONMU;
	public static short GRONMUPAIN;
	public static short GRONMUDIE;
	public static short GRONSHIELD;
	public static short SHIELD;
	
	public static void init()
	{
		if(!game.WH2) {
			KNIFEREADY = 1249;
			KNIFEATTACK = 1261;
			RFIST = 1268;
			SWORDATTACK = 1291;
			MORNINGSTAR = 1306;
			BOWREADY = 1313;
			BOWREADYEND = 1319;
			BOWWALK = 1323;
			KNIFEATTACK2 = 1329;
			SWORDPULL = 1333;
			SWORDATTACK2 = 1340;
			MORNINGATTACK2 = 1348;
			MUMEDUSA = 1353;
			MUTWOHANDS = 1363;
			BMUTWOHANDS = 1378;
			GOBSWORDPULL = 1390;
			GOBSWORDATTACK = 1397;
			GOBSWORDATTACK2 = 1404;
			BIGAXEATTACK = 1411;
			BIGAXEATTACK2 = 1421;
			BIGAXEDRAW = 1429;
			HALBERDATTACK1 = 1438;
			HALBERDATTACK2 = 1443;
			HALBERDDRAW = 1447;
			PIKEDRAW = 1451;
			PIKEATTACK1 = 1457;
			EXCALATTACK1 = 1463;
			EXCALATTACK2 = 1473;
			EXCALDRAW = 1481;
			BIGAXEDRAW9 = 1494;
			BIGAXEDRAW10 = 1495;
			GEARS2START = 1498;
			HORNEDSKULL = 1503;
			THEFONT = 1511;
			CRYSTALSTAFF = 1551;
			TORCH = 1554;
			WEAPON1 = 1567;
			WEAPON1A = 1571;
			AMULETOFTHEMIST = 1575;
			WEAPON2 = 1583;
			BRASSKEY = 1624;
			BLACKKEY = 1632;
			GLASSKEY = 1640;
			IVORYKEY = 1648;
			NEWCHUNK = 1664;
			BOWLOFFIRE = 1705;
			SPAWNFIREBALL = 1718;
			PENTAGRAM = 1760;
			THEHORN = 1768;
			BOW = 1776;
			SWINGGATE3 = 1789;
			PLATEARMOR = 1794;
			HELMET = 1802;
			CHAINMAIL = 1810;
			SCROLLSCARE = 1818;
			SCROLLNUKE = 1826;
			SCROLLFLY = 1834;
			SCROLLFIREBALL = 1842;
			SCROLLFREEZE = 1850;
			SCROLLNIGHT = 1858;
			SCROLLMAGIC = 1866;
			SCROLLOPEN = 1874;
			LEATHERARMOR = 1882;
			QUIVER = 1890;
			SWINGGATE4 = 1898;
			SWINGGATE5 = 1899;
			SMOKEFX = 1904;
			STANDINTORCH = 1908;
			PENTADOOR3 = 1927;
			PENTADOOR4 = 1928;
			PENTADOOR5 = 1929;
			PENTADOOR6 = 1930;
			PENTADOOR7 = 1931;
			SCARY = 1933;
			FISH = 1945;
			LEVERUP = 1947;
			LEVERDOWN = 1949;
			SPAWNJAVLIN = 1958;
			RAT = 1962;
			GUARDIAN = 1994;
			GUARDIANATTACK = 2002;
			DART = 2010;
			WEAPON4 = 2027;
			WEAPON6 = 2039;
			WEAPON5 = 2047;
			WEAPON5B = 2055;
			THROWHALBERD = 2066;
			WEAPON7 = 2067;
			THROWPIKE = 2071;
			EXPLO2 = 2096;
			SHATTERVASE = 2124;
			SHATTERVASE2 = 2131;
			SHATTERVASE3 = 2138;
			HANGMAN = 2145;
			SKELETON = 2156;
			SKELETONATTACK = 2181;
			SKELETONSKULL = 2186;
			SKELETONUP = 2191;
			SKELETONDIE = 2192;
			SKELETONDEAD = 2198;
			BONECHUNK1 = 2199;
			BONECHUNKEND = 2208;
			PIKEATTACK2 = 2209;
			GOBWEAPON = 2218;
			SFLASKBLUE = 2240;
			SFLASKGREEN = 2241;
			SFLASKOCHRE = 2242;
			SFLASKRED = 2243;
			SFLASKTAN = 2244;
			SFLASKBLACK = 2245;
			SHEALTHFONT = 2246;
			SSCOREFONT = 2256;
			SPOTIONFONT = 2266;
			SPOTIONBACKPIC = 2280;
			SPOTIONARROW = 2281;
			SSPELLBOOKBLANK = 2286;
			SSPELLBOOK2 = 2294;
			SSPELLBOOK3 = 2302;
			SSPELLBOOK4 = 2310;
			SSPELLBOOK5 = 2317;
			SSPELLBOOK6 = 2324;
			SSPELLBOOK7 = 2332;
			SSPELLBOOK8 = 2340;
			SARROWS = 2348;
			SPLAYERLVL = 2349;
			SSTATUSBAR = 2358;
			SKEYBLANK = 2359;
			SKEYBRASS = 2360;
			SKEYBLACK = 2361;
			SKEYGLASS = 2362;
			SKEYIVORY = 2363;
			SHEALTHBACK = 2365;
			SSCOREBACKPIC = 2368;
			SNDEFFECT = 2369;
			SNDLOOP = 2370;
			SNDLOOPOFF = 2371;
			BROWNCHUNKSTART = 2387;
			GREYCHUNKSTART = 2395;
			REDCHUNKSTART = 2403;
			GREENCHUNKSTART = 2411;
			TANCHUNKSTART = 2419;
			WILLOW = 2427;
			SPIKES = 2488;
			STHEFLAG = 2491;
			GRONHALATTACK = 2504;
			GRONHALATTACKEND = 2508;
			GROLHALREADY = 2509;
			GRONHALREADYEND = 2510;
			GRONHAL = 2539;
			GRONHALPAIN = 2559;
			GRONHALDIE = 2560;
			GRONSWATTACK = 2561;
			GRONSW = 2581;
			GRONSWPAIN = 2601;
			GRONSWDIE = 2602;
			GRONMUATTACK = 2603;
			GRONDIE = 2633;
			GRONDEAD = 2639;
			GRONMU = 2640;
			GRONMUPAIN = 2660;
			GRONMUDIE = 2661;
			GRONSHIELD = 2680;
			SHIELD = 2684;
		} else { //WH2
			KNIFEREADY = 1248;
			KNIFEATTACK = 1260;
			RFIST = 1267;
			SWORDATTACK = 1290;
			MORNINGSTAR = 1305;
			BOWREADY = 1312;
			BOWREADYEND = 1318;
			BOWWALK = 1322;
			KNIFEATTACK2 = 1328;
			SWORDPULL = 1332;
			SWORDATTACK2 = 1339;
			MORNINGATTACK2 = 1347;
			MUMEDUSA = 1352;
			MUTWOHANDS = 1362;
			BMUTWOHANDS = 1377;
			GOBSWORDPULL = 1389;
			GOBSWORDATTACK = 1396;
			GOBSWORDATTACK2 = 1403;
			BIGAXEATTACK = 1410;
			BIGAXEATTACK2 = 1420;
			BIGAXEDRAW = 1428;
			HALBERDATTACK1 = 1437;
			HALBERDATTACK2 = 1442;
			HALBERDDRAW = 1446;
			PIKEDRAW = 1450;
			PIKEATTACK1 = 1456;
			EXCALATTACK1 = 1462;
			EXCALATTACK2 = 1472;
			EXCALDRAW = 1480;
			BIGAXEDRAW9 = 1493;
			BIGAXEDRAW10 = 1494;
			GEARS2START = 1497;
			HORNEDSKULL = 1502;
			THEFONT = 1510;
			CRYSTALSTAFF = 1550;
			TORCH = 1553;
			WEAPON1 = 1566;
			WEAPON1A = 1570;
			AMULETOFTHEMIST = 1574;
			WEAPON2 = 1582;
			BRASSKEY = 1623;
			BLACKKEY = 1631;
			GLASSKEY = 1639;
			IVORYKEY = 1647;
			NEWCHUNK = 1663;
			BOWLOFFIRE = 1704;
			SPAWNFIREBALL = 1717;
			PENTAGRAM = 1759;
			THEHORN = 1767;
			BOW = 1775;
			SWINGGATE3 = 1788;
			PLATEARMOR = 1793;
			HELMET = 1801;
			CHAINMAIL = 1809;
			SCROLLSCARE = 1817;
			SCROLLNUKE = 1825;
			SCROLLFLY = 1833;
			SCROLLFIREBALL = 1841;
			SCROLLFREEZE = 1849;
			SCROLLNIGHT = 1857;
			SCROLLMAGIC = 1865;
			SCROLLOPEN = 1873;
			LEATHERARMOR = 1881;
			QUIVER = 1889;
			SWINGGATE4 = 1897;
			SWINGGATE5 = 1898;
			SMOKEFX = 1903;
			STANDINTORCH = 1907;
			PENTADOOR3 = 1926;
			PENTADOOR4 = 1927;
			PENTADOOR5 = 1928;
			PENTADOOR6 = 1929;
			PENTADOOR7 = 1930;
			SCARY = 1932;
			FISH = 1944;
			LEVERUP = 1946;
			LEVERDOWN = 1948;
			SPAWNJAVLIN = 1957;
			RAT = 1961;
			GUARDIAN = 1993;
			GUARDIANATTACK = 2001;
			DART = 2009;
			WEAPON4 = 2026;
			WEAPON6 = 2038;
			WEAPON5 = 2046;
			WEAPON5B = 2054;
			THROWHALBERD = 2065;
			WEAPON7 = 2066;
			THROWPIKE = 2070;
			EXPLO2 = 2095;
			SHATTERVASE = 2123;
			SHATTERVASE2 = 2130;
			SHATTERVASE3 = 2137;
			HANGMAN = 2144;
			SKELETON = 2155;
			SKELETONATTACK = 2180;
			SKELETONSKULL = 2185;
			SKELETONUP = 2190;
			SKELETONDIE = 2191;
			SKELETONDEAD = 2197;
			BONECHUNK1 = 2198;
			BONECHUNKEND = 2207;
			PIKEATTACK2 = 2208;
			GOBWEAPON = 2217;
			SFLASKBLUE = 2239;
			SFLASKGREEN = 2240;
			SFLASKOCHRE = 2241;
			SFLASKRED = 2242;
			SFLASKTAN = 2243;
			SFLASKBLACK = 2244;
			SHEALTHFONT = 2245;
			SSCOREFONT = 2255;
			SPOTIONFONT = 2265;
			SPOTIONBACKPIC = 2279;
			SPOTIONARROW = 2280;
			SSPELLBOOKBLANK = 2285;
			SSPELLBOOK2 = 2293;
			SSPELLBOOK3 = 2301;
			SSPELLBOOK4 = 2309;
			SSPELLBOOK5 = 2316;
			SSPELLBOOK6 = 2323;
			SSPELLBOOK7 = 2331;
			SSPELLBOOK8 = 2339;
			SARROWS = 2347;
			SPLAYERLVL = 2348;
			SSTATUSBAR = 2357;
			SKEYBLANK = 2358;
			SKEYBRASS = 2359;
			SKEYBLACK = 2360;
			SKEYGLASS = 2361;
			SKEYIVORY = 2362;
			SHEALTHBACK = 2364;
			SSCOREBACKPIC = 2367;
			SNDEFFECT = 2368;
			SNDLOOP = 2369;
			SNDLOOPOFF = 2370;
			BROWNCHUNKSTART = 2386;
			GREYCHUNKSTART = 2394;
			REDCHUNKSTART = 2402;
			GREENCHUNKSTART = 2410;
			TANCHUNKSTART = 2418;
			WILLOW = 2426;
			SPIKES = 2487;
			STHEFLAG = 2490;
			GRONHALATTACK = 2502;
			GRONHALATTACKEND = 2506;
			GROLHALREADY = 2507;
			GRONHALREADYEND = 2508;
			GRONHAL = 2537;
			GRONHALPAIN = 2557;
			GRONHALDIE = 2558;
			GRONSWATTACK = 2559;
			GRONSW = 2579;
			GRONSWPAIN = 2599;
			GRONSWDIE = 2600;
			GRONMUATTACK = 2601;
			GRONDIE = 2631;
			GRONDEAD = 2637;
			GRONMU = 2638;
			GRONMUPAIN = 2658;
			GRONMUDIE = 2659;
			GRONSHIELD = 2678;
			SHIELD = 2682;
		}
	}
}
